language: python

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src

install:
    - pip install wheel
    - pip install -U platformio
    - platformio platform install native
    - platformio update

addons:
    apt:
        packages:
            - doxygen

script:
    # check for trailing white spaces (comparing with first commit in git log)
    - git diff --check `git rev-list HEAD | tail -n 1`..
    - platformio run -e mppt_2420_lc -e mppt_1210_hus -e mppt_2420_hc -e pwm_2420_lus
    - platformio test -e unit_test
    - platformio check -e mppt_1210_hus -e pwm_2420_lus --skip-packages --fail-on-defect high
    - doxygen Doxyfile

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: html
    github_token: $GH_REPO_TOKEN
    on:
        repo: LibreSolar/charge-controller-firmware
        branch: main
